In [1]:
mylist=[]
for x in range (2000,3201,1):
    if ((x%7)==0) and ((x%5)!=0 ):
        mylist.append(x)
print(mylist )

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [1]:
def factoriel(p):
    s=1
    for y in range(1,p+1):
       s*=y
    return(s)
x=int(input('zertyu'))
factoriel(x)

zertyu 8


40320

In [ ]:
def carre(p):
    mydict={}
    for x in range(1,p+1,1):
        mydict[x]=x*x
    print(mydict)    
p=int(input())
carre(p)
        
        

In [2]:
def missing(ch,p):
    return (ch[0:p]+ch[p+1:len(ch)])
ch=input()     
p=int(input())
print(missing(ch,p))

 kitten
 1


ktten


In [10]:
import numpy as np 
new_array=np.array([[0, 1], [2 ,3] ,[4 ,5]] )
print(new_array)
new_list=new_array.tolist()
print(new_array)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [12]:
import numpy as np 
array1=np.array([0 ,1 ,2] )
array2=np.array([2,1,0])
print(array1)
print(array2)
print(np.cov(array1,array2))

[0 1 2]
[2 1 0]
[[ 1. -1.]
 [-1.  1.]]


In [14]:

def fonction(c,d,h):
    import math
    q=math.sqrt((2 * c * d)/h )
c=50
h=30
ch=input()
ch1=' '
for i in range(1,3,1):
    d=int(ch[0:ch.find(',')])
    print(d)
    p=ch.find(',')
    ch.replace(ch[0:p],' ')
    print(ch)
    fonction(c,d,h)
    ch1=ch1+str(d)+' ,'
print(ch1)   
    
        

  
    

 120,150,180


120
120,150,180
120
120,150,180
 120 ,120 ,
